// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6xMrjbYkKpkwwJytZnQ4gbRo28b58CI',
    appId: '1:299384709451:web:e462781066a59c8b3ac8ce',
    messagingSenderId: '299384709451',
    projectId: 'interview-8503e',
    authDomain: 'interview-8503e.firebaseapp.com',
    storageBucket: 'interview-8503e.firebasestorage.app',
    measurementId: 'G-L2M86SEKJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kT7t0sp4o7jHDqd-Z07tDawc20EPDWA',
    appId: '1:299384709451:android:4b8c93c0e88e35633ac8ce',
    messagingSenderId: '299384709451',
    projectId: 'interview-8503e',
    storageBucket: 'interview-8503e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxOV9s-3k_TNaz58266Zre-k16MKvbDs',
    appId: '1:299384709451:ios:6a07690126b97d4d3ac8ce',
    messagingSenderId: '299384709451',
    projectId: 'interview-8503e',
    storageBucket: 'interview-8503e.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxOV9s-3k_TNaz58266Zre-k16MKvbDs',
    appId: '1:299384709451:ios:6a07690126b97d4d3ac8ce',
    messagingSenderId: '299384709451',
    projectId: 'interview-8503e',
    storageBucket: 'interview-8503e.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA6xMrjbYkKpkwwJytZnQ4gbRo28b58CI',
    appId: '1:299384709451:web:9f3ab226fd92f7263ac8ce',
    messagingSenderId: '299384709451',
    projectId: 'interview-8503e',
    authDomain: 'interview-8503e.firebaseapp.com',
    storageBucket: 'interview-8503e.firebasestorage.app',
    measurementId: 'G-88T5Q5MFED',
  );
}
